version: '3'

volumes:
  postgres_data:

services:
  postgres:
    image: sql_ex_postgres:16-alpine
    environment:
      POSTGRES_DB: db_pg
      POSTGRES_USER: user_pg
      POSTGRES_PASSWORD: pass_pg
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
